import avatar1 from "../src/assets/images/1.png";
import avatar2 from "../src/assets/images/2.png";
import avatar3 from "../src/assets/images/3.png";
import avatar4 from "../src/assets/images/4.png";
import avatar5 from "../src/assets/icons/emptyAvatar.svg";
import avatar6 from "../src/assets/images/6.png";
import avatar7 from "../src/assets/images/7.png";
import avatar8 from "../src/assets/images/8.png";
import avatar9 from "../src/assets/images/9.png";

export const users = [
  {
    id: 1,
    name: "Кравцова Александра",
    image: avatar1,
    age: 26,
    gender: "жен",
    hasNewMessage: true,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 2,
    name: "Рожков Денис ",
    image: avatar2,
    age: 30,
    gender: "муж",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 3,
    name: "Кравцова Александра",
    image: avatar1,
    age: 28,
    gender: "жен",
    hasNewMessage: false,
    hasNotification: true,
    isChecked: false,
  },
  {
    id: 4,
    name: "Диброва Алевтина",
    image: avatar3,
    age: 22,
    gender: "жен",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 5,
    name: "Иванов Дмитрий",
    image: avatar4,
    age: 29,
    gender: "муж",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 6,
    name: "nosikov@list.ru",
    image: avatar5,
    age: 29,
    gender: "муж",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 7,
    name: "Ахмедов Артур",
    image: avatar6,
    age: 29,
    gender: "муж",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 8,
    name: "Блажевич Артур",
    image: avatar7,
    age: 32,
    gender: "муж",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 9,
    name: "Валиева Руфина",
    image: avatar8,
    age: 33,
    gender: "жен",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 10,
    name: "Волошина Виктория",
    image: avatar9,
    age: 30,
    gender: "жен",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
  {
    id: 11,
    name: "Волошина Виктория",
    image: avatar9,
    age: 31,
    gender: "жен",
    hasNewMessage: false,
    hasNotification: false,
    isChecked: false,
  },
];
